#################################################
# Makefile
#################################################

job-debian10-makefile-gcc:

  tags: [ "docker-debian10" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian:10
  except:
    variables:
      - $DEPLOY_RUN
      - $DEPLOY_UBUNTU
  variables:
    CMAKE_GENERATOR: Unix Makefiles
    CC: gcc
    CXX: g++
    ADDITIONAL_BUILD_OPTIONS: -j$MAKEFILE_JOBS
  extends: .scheduled-job-linux


job-debian10-makefile-clang:

  tags: [ "docker-debian10" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian:10
  except:
    variables:
      - $DEPLOY_RUN
      - $DEPLOY_UBUNTU
  variables:
    CMAKE_GENERATOR: Unix Makefiles
    CC: clang
    CXX: clang++
    ADDITIONAL_BUILD_OPTIONS: -j$MAKEFILE_JOBS
  extends: .scheduled-job-linux

#################################################
# Ninja
#################################################

job-debian10-ninja-gcc:

  tags: [ "docker-debian10" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian:10
  except:
    variables:
      - $DEPLOY_RUN
      - $DEPLOY_UBUNTU
  variables:
    CMAKE_GENERATOR: Ninja
    CC: gcc
    CXX: g++
  extends: .scheduled-job-linux


job-debian10-ninja-clang:

  tags: [ "docker-debian10" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian:10
  except:
    variables:
      - $DEPLOY_RUN
      - $DEPLOY_UBUNTU
  variables:
    CMAKE_GENERATOR: Ninja
    CC: clang
    CXX: clang++
  extends: .job-linux

#################################################
# DEB
#################################################

job-debian10-deb:

  tags: [ "docker-debian10" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian:10
  extends: .job-linux-deb
  except:
    variables:
      - $DEPLOY_UBUNTU


job-debian10-deb-deploy:

  except:
    variables:
      - $DEPLOY_UBUNTU
  variables:
    RELEASE: stretch
    FREIGHT_PATH: $DEBIAN_FREIGHT_CONF_PATH
  extends: .job-debian-deb-deploy
  dependencies:
    - job-debian10-deb
