
job-debian9-yocto-sumo:
  stage: build
  tags: [ "docker-debian9" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-flexisip-yocto:latest
#  only:
#    variables:
#      - $NIGHTLY_MASTER
  cache:
    key: yocto-cache-key
    paths:
      - yocto_build/tmp/
      - yocto_build/deploy/
      - yocto_build/work/
      - yocto_build/work-shared/
      - yocto_build/sstate-cache/
      - yocto_build/downloads/
  before_script:
    - ln -sf ./yocto_build /home/build/poky/build
  script:
    - export ORIGIN_PATH="$(pwd)"
    - cd /home/build/poky
    - source oe-init-build-env
    - bitbake -f flexisip 2>&1 | tee bitbake_build.log
    - cd $ORIGIN_PATH
    - pwd
    - ln -sf /home/build/poky/build ./yoto_build
#Gitlab doesn't handle cache and artifacts paths
  artifacts:
    paths:
      - yocto_build/bitbake_build.log
      - yocto_build/tmp/deploy/ipk/**/flexisip*.ipk
